---

secrets:
  cloudflare-token:
    file: ./secrets/cloudflare-token.secret
  cloudflare-email:
    file: ./secrets/cloudflare-email.secret
  openvpn_user:
    file: ./secrets/openvpn_user.secret
  openvpn_password:
    file: ./secrets/openvpn_password.secret

services:
  gluetun:
    # See more: https://github.com/qdm12/gluetun-wiki
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Expose ports for services using this network
      - "8989:8989"  # Sonarr
      - "7878:7878"  # Radarr
      - "9696:9696"  # Prowlarr
      - "8088:8088"  # qBittorrent
    secrets:
      - openvpn_user
      - openvpn_password
    env_file: ./env/gluetun.env
    volumes:
      - gluetun:/gluetun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 127.0.0.1
      - 1.1.1.1

  watchtower:
    # See more: https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    container_name: watchtower
    env_file: ./env/watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

include:
  - bittorrent-compose.yml
  - arr-compose.yml
  - plex-compose.yml
  - jellyfin-compose.yml

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  gluetun: # Gluetun app data.
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NFS_VOLUME}/docker_data/gluetun"