---

secrets:
  plex-claim:
    file: ./secrets/plex-claim.secret

services:
  overseerr:
    # See more: https://docs.overseerr.dev/getting-started/installation
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: always
    ports:
      - "5055:5055"
    env_file: ./env/plex.env
    volumes:
      - overseerr:/app/config
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      plex:
        condition: service_healthy
        restart: true

  plex:
    # See more: https://docs.linuxserver.io/images/docker-plex/
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
    secrets:
      - plex-claim
    env_file: ./env/plex.env
    volumes:
      - plex:/config
      - media:/media
    healthcheck:
      test: curl -f http://localhost:32400/identity || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  media: # Media library
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NFS_VOLUME}/data/media"

  overseerr: # Overseerr app data.
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NFS_VOLUME}/docker_data/overseerr"

  plex: # Plex app data.
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${NFS_VOLUME}/docker_data/plex"